// Lista de departamentos del Perú con códigos ISO 3166-2
export const departamentos = [
  { id: "PE-AMA", nombre: "Amazonas" },
  { id: "PE-ANC", nombre: "Áncash" },
  { id: "PE-APU", nombre: "Apurímac" },
  { id: "PE-ARE", nombre: "Arequipa" },
  { id: "PE-AYA", nombre: "Ayacucho" },
  { id: "PE-CAJ", nombre: "Cajamarca" },
  { id: "PE-CAL", nombre: "Callao" },
  { id: "PE-CUS", nombre: "Cusco" },
  { id: "PE-HUV", nombre: "Huancavelica" },
  { id: "PE-HUC", nombre: "Huánuco" },
  { id: "PE-ICA", nombre: "Ica" },
  { id: "PE-JUN", nombre: "Junín" },
  { id: "PE-LAL", nombre: "La Libertad" },
  { id: "PE-LAM", nombre: "Lambayeque" },
  { id: "PE-LIM", nombre: "Lima" },
  { id: "PE-LOR", nombre: "Loreto" },
  { id: "PE-MDD", nombre: "Madre de Dios" },
  { id: "PE-MOQ", nombre: "Moquegua" },
  { id: "PE-PAS", nombre: "Pasco" },
  { id: "PE-PIU", nombre: "Piura" },
  { id: "PE-PUN", nombre: "Puno" },
  { id: "PE-SAM", nombre: "San Martín" },
  { id: "PE-TAC", nombre: "Tacna" },
  { id: "PE-TUM", nombre: "Tumbes" },
  { id: "PE-UCA", nombre: "Ucayali" },
  { id: "PE-LMA", nombre: "Municipalidad Metropolitana de Lima" }
];
