# Etapa base: Node
FROM node:20-alpine AS base
WORKDIR /usr/src/app

# Copiar package.json y package-lock.json (si existe)
COPY package*.json ./

# Instalar dependencias
RUN npm install

# Copiar el resto del código
COPY . .

# Exponer el puerto de Nest (por defecto 3000)
EXPOSE 3000

# Comando por defecto (modo desarrollo con hot reload)
CMD ["npm", "run", "start:dev"]
